- name: Setup Ubuntu droplet
  hosts: webservers
  gather_facts: no
  vars:
    - ansible_connection: local
    - ansible_python_interpreter: python
  tasks:
    - name: create ubuntu 14.04 droplet on digital_ocean
      digital_ocean: >
        state=present
        command=droplet
        name={{ inventory_hostname }}
        api_token="{{ do_api_token }}"
        size_id=512mb
        region_id=fra1
        image_id=11836690
        wait=yes
        unique_name=yes
        ssh_key_ids=912686
      register: new_droplet
      always_run: yes

    - name: register real root user to localhost facts
      set_fact: ansible_ssh_host="{{ new_droplet.droplet.ip_address }}"

    - wait_for: host={{ new_droplet.droplet.ip_address }} port=22 delay=30 state=started

    - name: retrieve key from distant host
      command: ssh-keyscan "{{ ansible_ssh_host }}"
      register: key_scan_result
      failed_when: false
      changed_when: false

    - debug: msg="{{ key_scan_result.stdout }}"

    - name: check if distant host key to known_hosts
      command: "grep \"{{ key_scan_result.stdout }}\" ~/.ssh/known_hosts"
      register: key_is_present
      changed_when: key_is_present.rc != 0
      failed_when: false

    - name: remove previously registered key to known_hosts
      known_hosts: path='~/.ssh/known_hosts'
                   host='{{ ansible_ssh_host }}'
                   state=absent
      when: key_is_present.rc != 0

    - name: register distant host key to known_hosts
      known_hosts: path='~/.ssh/known_hosts'
                   host='{{ ansible_ssh_host }}'
                   key="{{ key_scan_result.stdout }}"
                   state=present
      when: key_is_present.rc != 0

    - pause: seconds=10

    - name: try to ssh with root user
      command: ssh -oBatchMode=yes {{ distant_root_name }}@{{ ansible_ssh_host }} 'echo {{ distant_root_name }}'
      register: root_ssh_cmd_result
      ignore_errors: true
      changed_when: false

    - name: register real root user to localhost facts
      set_fact: ansible_ssh_user="{{ root_ssh_cmd_result.stdout }}"
      when: root_ssh_cmd_result.rc == 0

    - name: try to ssh with other user
      command: ssh -oBatchMode=yes {{ distant_admin_name }}@{{ ansible_ssh_host }} 'echo {{ distant_admin_name }}'
      register: admin_ssh_cmd_result
      ignore_errors: true
      changed_when: false
      when: root_ssh_cmd_result.rc != 0

    - name: register real root user to localhost facts
      set_fact: ansible_ssh_user="{{ admin_ssh_cmd_result.stdout }}"
      when: root_ssh_cmd_result.rc != 0 and admin_ssh_cmd_result.rc == 0

    - debug: msg="{{ ansible_ssh_user }}"

- name: Setup Ubuntu droplet
  hosts: webservers
  gather_facts: yes
  sudo: yes
  pre_tasks:
    - name: install dependencies
      apt: pkg={{ item }} update_cache=yes
      with_items:
        - build-essential
        - openssl
        - libssl-dev
        - pkg-config
        - whois
        - git
        - apt-transport-https
        - ca-certificates

    # Setup user
    - name: Create user
      user:
        name: '{{ user_name }}'
        comment: '{{ user_comment }}'
        password: '{{ user_password }}'
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        groups: 'sudo'

    - name: Create ssh folder
      file: path='/home/{{ user_name }}/.ssh' state=directory mode=0700

    - name: Add public key to authorized key
      lineinfile:
        dest: "/home/{{ user_name }}/.ssh/authorized_keys"
        line: "{{ public_key }}"
        state: present
        create: yes
        backup: yes

    # Last configuration for ssh. Disable access with root user
    - name: Disable root login via ssh
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin (yes|no)$" line="PermitRootLogin no"
      notify:
        - service ssh restart
  roles:
    - ntp
    - nodejs
    - apache2
    - passenger
    - ufw

  handlers:
    - name: service ssh restart
      command: service ssh restart
      register: ssh_service_restart
      failed_when: ssh_service_restart.rc != 0
      changed_when: false
