- name: Setup Ubuntu droplet
  hosts: webservers
  gather_facts: no
  vars:
    - ansible_connection: local
    - ansible_python_interpreter: python
  tasks:
    - name: destroy ubuntu 14.04 droplet on digital_ocean
      digital_ocean: >
        name={{ inventory_hostname }}
        state=absent
        api_token="{{ do_api_token }}"
        unique_name=yes
        wait_timeout=500
      register: destroy_result

    - pause: seconds=40
